import type { Metadata, Viewport } from "next";
import { Toaster } from "sonner";
import { fontMono, fontSans } from "./fonts";
import { seo, profile } from "@/data/resume";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SmoothScroll } from "@/components/providers/SmoothScroll";
import { Navbar } from "@/components/layout/Navbar";
import { Preloader } from "@/components/Preloader";
import { ScrollProgress } from "@/components/ScrollProgress";
import { BackToTop } from "@/components/BackToTop";
import { CommandPalette } from "@/components/CommandPalette";
import { CustomCursor } from "@/components/effects/CustomCursor";
import { MouseGlow } from "@/components/effects/MouseGlow";
import { NoiseOverlay } from "@/components/effects/Backgrounds";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(seo.url),
  title: {
    default: seo.title,
    template: `%s · ${profile.name}`,
  },
  description: seo.description,
  keywords: seo.keywords,
  authors: [{ name: profile.name }],
  creator: profile.name,
  applicationName: seo.siteName,
  openGraph: {
    type: "website",
    locale: "en_US",
    url: seo.url,
    siteName: seo.siteName,
    title: seo.title,
    description: seo.description,
    // Social card is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: seo.title,
    description: seo.description,
    creator: "@vaibhav449",
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
  robots: { index: true, follow: true },
  alternates: { canonical: seo.url },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0c" },
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
  ],
  width: "device-width",
  initialScale: 1,
};

// Structured data (JSON-LD) for rich search results.
const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: profile.name,
  jobTitle: profile.title,
  email: `mailto:${profile.email}`,
  url: seo.url,
  address: { "@type": "PostalAddress", addressLocality: profile.location },
  sameAs: [
    "https://github.com/vaibhav449",
    "https://www.linkedin.com/in/vaibhav-chaubey-00a774329",
    "https://leetcode.com/u/Vaibhavchaubey007/",
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fontSans.variable} ${fontMono.variable}`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }}
        />
      </head>
      <body className="min-h-screen bg-background text-foreground selection:bg-electric/30">
        <ThemeProvider>
          <SmoothScroll>
            <Preloader />
            <MouseGlow />
            <NoiseOverlay />
            <ScrollProgress />
            <Navbar />
            <CommandPalette />
            <CustomCursor />
            <main className="relative">{children}</main>
            <BackToTop />
            <Toaster
              position="bottom-center"
              theme="dark"
              toastOptions={{
                classNames: {
                  toast:
                    "!bg-card !border-border !text-foreground !rounded-xl",
                },
              }}
            />
          </SmoothScroll>
        </ThemeProvider>
      </body>
    </html>
  );
}
